services:
  jobcrawliya:
    build: .
    container_name: jobcrawliya_app
    volumes:
      - ./:/usr/src/app
      - ./data/scraped:/usr/src/app/data/scraped
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    shm_size: '1gb'
